### ISSUE TITLE
HW#4 Code review

### ISSUE THREAD

**Issue by khit-mle** [mlteamurfu2325/practicum-s1#50]
In reporting on our homework No. 4 assignment we need to highlight two parts:

1. While working on homework No. 3 we took into account requirements from homework No. 4 and thus we can present the next table that contains information on code-reviewed refactoring changes to our codebase:

| Idea                                                        | Issue                                                                | Pull Request                                                    | Assigned to  | Reviewer No. 1 | Reviewer No. 2 |
|-------------------------------------------------------------|----------------------------------------------------------------------|-----------------------------------------------------------------|--------------|----------------|----------------|
| Refactor deploy/download_faster_whisper_models.py           | [Issue#41](https://github.com/mlteamurfu2325/practicum-s1/issues/41) | [PR#42](https://github.com/mlteamurfu2325/practicum-s1/pull/42) | @DanilKhardi | @ANGorbachev   | @khit-mle      |
| Refactor src/llm_summ/summ_fetcher.py                       | [Issue#39](https://github.com/mlteamurfu2325/practicum-s1/issues/39) | [PR#40](https://github.com/mlteamurfu2325/practicum-s1/pull/40) | @alexa313    | @LenaIkra      | @khit-mle      |
| Refactor cuda_checker.py and data_validator.py in src/utils | [Issue#43](https://github.com/mlteamurfu2325/practicum-s1/issues/43) | [PR#44](https://github.com/mlteamurfu2325/practicum-s1/pull/44) | @ANGorbachev | @alexa313      | @LenaIkra      |
| Refactor upload_file_saver.py in src/utils                  | [Issue#45](https://github.com/mlteamurfu2325/practicum-s1/issues/45) | [PR#47](https://github.com/mlteamurfu2325/practicum-s1/pull/47) | @LenaIkra    | @DanilKhardi   | @khit-mle      |
| Improve app install via a bash script                       | [Issue#46](https://github.com/mlteamurfu2325/practicum-s1/issues/46) | [PR#48](https://github.com/mlteamurfu2325/practicum-s1/pull/48) | @khit-mle    | @DanilKhardi   | @LenaIkra      |

2. We can also showcase some PRs from our consequent changes that we made in order to accomplish this semester's overall goals of improving our project:

| Topic                                                     | Issue                                                                | Pull Request                                                    | Assigned to  | Reviewer No. 1 | Reviewer No. 2 |
|-----------------------------------------------------------|----------------------------------------------------------------------|-----------------------------------------------------------------|--------------|----------------|----------------|
| test: add test for summ_fetcher.py                        | [Issue#58](https://github.com/mlteamurfu2325/practicum-s1/issues/58) | [PR#59](https://github.com/mlteamurfu2325/practicum-s1/pull/59) | @khit-mle    | @alexa313      | @LenaIkra      |
| feat: add model selection for LLM summarization in app UI | [Issue#56](https://github.com/mlteamurfu2325/practicum-s1/issues/56) | [PR#57](https://github.com/mlteamurfu2325/practicum-s1/pull/57) | @ANGorbachev | @DanilKhardi    | @khit-mle      |
| cd: add Dockerfile and autobuild to ghcr.io               | [Issue#62](https://github.com/mlteamurfu2325/practicum-s1/issues/62) | [PR#55](https://github.com/mlteamurfu2325/practicum-s1/pull/55) | @LenaIkra    | @alexa313      | @khit-mle      |
| cd: fix cleanup logic install.sh                          | [Issue#53](https://github.com/mlteamurfu2325/practicum-s1/issues/53) | [PR#52](https://github.com/mlteamurfu2325/practicum-s1/pull/52) | @DanilKhardi | @alexa313      | @khit-mle      |

**We've prepared a check list to self-assess whether we've adhered to the homework No. 4's criteria:**
- [x] we've selected a specific GitHub repo to work on
- [x] all members of our team were added as collaborators
- [x] every member has created at least one branch and committed changes to it
- [x] every member has created at least one PR to merge that branch into `main`
- [x] two other members has code-reviewed that branch
- [x] upon successful passing code review that branch was merged into `main`
